---
- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

# To Do: Implement your workload deployment tasks here
# -------------------------------------------------------------------------

- name: Install podman
  ansible.builtin.package:
    name: podman
    state: present

- name: Clone the Lab repo
  git:
    repo: "{{ ocp4_workload_ai_llm_rag_demo_claim_repo_url }}"
    dest: "/tmp/ocp4_workload_ai_llm_rag_demo_claim_repo"
    version: "{{ ocp4_workload_ai_llm_rag_demo_claim_branch }}"
  register: git_clone

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
